#!/usr/bin/env python3
from PyQt5 import QtWidgets, QtCore, QtGui
import serial
import time
import struct
import sys

def send_color(r,g,b):
  pkt=b'\x80'
  for i in range(0, 1):
    pkt += struct.pack("BBB", int(r / 2), int(g / 2), int(b / 2))
  s.write(pkt)

s = serial.Serial('/dev/ttyUSB0', 19200)
send_color(0, 0, 0)

app = QtWidgets.QApplication(sys.argv)
picker = QtWidgets.QColorDialog()

def update_color(color):
  r, g, b, a = picker.currentColor().getRgb()
  send_color(int(r), int(g), int(b))

picker.currentColorChanged.connect(update_color)
picker.open()
exit(app.exec())
